import streamlit as st
import requests
import pandas as pd

# ==========================================
# CONFIGURATION SEC
# ==========================================
USER_AGENT = "Jeremy Cassagne (jcassagne75@gmail.com)"
HEADERS = {"User-Agent": USER_AGENT}
DEAL_CIK = "0001967111"  # Ford Credit Auto Owner Trust 2023-A

@st.cache_data
def fetch_sec_data(cik):
    formatted_cik = str(cik).zfill(10)
    url = f"https://data.sec.gov/submissions/CIK{formatted_cik}.json"
    response = requests.get(url, headers=HEADERS)
    if response.status_code != 200: return None, None
    data = response.json()
    deal_name = data.get("name", "Nom inconnu")
    filings = data.get("filings", {}).get("recent", {})
    results = []
    for i in range(len(filings.get("form", []))):
        form_type = filings["form"][i]
        if form_type in ["10-D", "ABS-EE"]:
            acc_num = filings["accessionNumber"][i].replace("-", "")
            doc = filings["primaryDocument"][i]
            results.append({
                "Reporting Date": filings["reportDate"][i],
                "Form Type": form_type,
                "Document Link": f"https://www.sec.gov/Archives/edgar/data/{formatted_cik}/{acc_num}/{doc}"
            })
            if len(results) >= 12: break
    return deal_name, pd.DataFrame(results)

# ==========================================
# INTERFACE UTILISATEUR & STRESS ENGINE
# ==========================================
st.set_page_config(page_title="ABS Surveillance Platform", layout="wide")

st.title("🏦 Structured Finance Surveillance Platform")
st.subheader("Auto ABS & ABCP Digital Twin")
st.markdown("---")

# 1. PANNEAU LATÉRAL (SIDEBAR) : Paramètres de Stress
st.sidebar.header("🌪️ Macro Stress Engine")
st.sidebar.markdown("Test the transaction's resilience against macro shocks.")

cdr_shock = st.sidebar.slider(
    "Annualized Default Rate (CDR %)", 
    min_value=0.0, max_value=15.0, value=1.5, step=0.5,
    help="Constant Default Rate: The annualized percentage of the loan pool balance that defaults. Higher CDR directly eats into the Overcollateralization cushion."
)

cpr_shock = st.sidebar.slider(
    "Prepayment Speed (CPR %)", 
    min_value=0.0, max_value=30.0, value=8.0, step=1.0,
    help="Constant Prepayment Rate: The annualized rate at which borrowers pay back their loans early. High CPR reduces the yield (Excess Spread) generated by the portfolio."
)

recovery_rate = st.sidebar.slider(
    "Recovery Rate (%)", 
    min_value=10, max_value=80, value=50, step=5,
    help="The percentage of the defaulted loan balance recovered (e.g., by repossessing and selling the vehicle). Net Loss = Gross Default * (1 - Recovery Rate)."
)

st.sidebar.markdown("---")
st.sidebar.info("💡 **ABCP Liquidity Note**: High defaults coupled with low recoveries will deplete the Overcollateralization (OC) cushion, potentially triggering a Liquidity Facility Draw.")

# 2. APPEL API & MOTEUR DE CALCUL 
deal_name, df_filings = fetch_sec_data(DEAL_CIK)

if df_filings is not None:
    st.success(f"✅ Connection to SEC EDGAR successful. Active Deal: **{deal_name}**")
    
    # Lecture des données réelles issues du pipeline ETL
    import json
    try:
        with open("live_metrics.json", "r") as f:
            live_data = json.load(f)
            base_pool_balance = live_data["current_pool_balance"]
            base_oc_ratio = live_data["current_oc"]
            target_oc = live_data["target_oc"]
            report_date = live_data["report_date"]
            st.caption(f"🔄 Data last refreshed from SEC EDGAR: **{report_date}**")
    except FileNotFoundError:
        st.error("⚠️ Data pipeline not synced. Please run etl_pipeline.py first.")
        st.stop()
    
    projected_gross_losses = base_pool_balance * (cdr_shock / 100)
    projected_net_losses = projected_gross_losses * (1 - (recovery_rate / 100))
    stressed_oc = base_oc_ratio - ((projected_net_losses / base_pool_balance) * 100)
    
    col1, col2 = st.columns([2, 1.2])
    
    with col1:
        st.write("### 📄 Latest Deal Reports (SEC Filings)")
        st.dataframe(df_filings, column_config={"Document Link": st.column_config.LinkColumn("SEC Link")}, hide_index=True, use_container_width=True)
        
        st.write("### 📉 Projected Pool Amortization under Stress")
        periods = list(range(1, 25))
        amortization = [base_pool_balance * ((1 - (cpr_shock/100)/12) ** p) - (projected_net_losses/24 * p) for p in periods]
        df_chart = pd.DataFrame({"Month": periods, "Stressed Pool Balance ($)": amortization}).set_index("Month")
        st.line_chart(df_chart)

    with col2:
        st.write("### ⚙️ Live Stress Metrics")
        
        st.metric(
            label="Current Pool Balance", 
            value=f"${base_pool_balance:,.0f}",
            help="The total principal amount currently outstanding on the underlying auto loans."
        )
        
        oc_delta = stressed_oc - base_oc_ratio
        st.metric(
            label="Stressed Overcollateralization (OC)", 
            value=f"{stressed_oc:.2f}%", 
            delta=f"{oc_delta:.2f}%",
            help="OC is the amount by which the collateral balance exceeds the issued notes. It is the primary credit enhancement protecting investors from losses."
        )
        
        st.metric(
            label="Projected 12m Net Losses", 
            value=f"${projected_net_losses:,.0f}",
            help="Expected unrecoverable dollar losses over the next 12 months based on your CDR and Recovery Rate stress inputs."
        )
        
        st.markdown("---")
        st.write("### 🚨 Structural Triggers & Conduit Impact")
        
        if stressed_oc < target_oc:
            st.error(f"**OC Target Breach!** Stressed OC ({stressed_oc:.2f}%) fell below target ({target_oc}%).")
            st.warning("**Liquidity Alert**: ABCP sponsor facility draw probability increased due to stop-issuance triggers.")
        else:
            st.success(f"**OC Target Intact.** Cushion remaining: {stressed_oc - target_oc:.2f}%")

    # 3. EXPLICATION BUSINESS POUR LE RECRUTEUR
    st.markdown("---")
    with st.expander("📖 Business Impact: What does this mean for the ABCP Conduit?"):
        st.markdown("""
        **How these metrics impact the Sponsor Bank (Liquidity Provider):**
        * **Collateral Deterioration (High CDR):** When the underlying auto loans default rapidly, the Overcollateralization (OC) cushion shrinks.
        * **Trigger Breach:** If the OC drops below the structural target (12.0%), the transaction enters a protective state. Cash flows normally paid to the equity holder (seller) are diverted to pay down senior debt.
        * **Commercial Paper (CP) Freeze:** In an ABCP Conduit structure, a breach of collateral performance triggers often prevents the SPV from issuing new Commercial Paper to rollover maturing debt.
        * **The Liquidity Draw:** If the CP market freezes or triggers are breached, the Conduit must draw on its backup **Liquidity Facility** provided by the sponsor bank to repay maturing CP, transferring the credit and funding risk back to the bank's balance sheet.
        """)

        # 4. DOCUMENTATION METHODOLOGIQUE
    with st.expander("🔬 Data Architecture & Calculation Methodology"):
        st.markdown("""
        **1. Data Ingestion Pipeline:**
        * **Source:** Live connection to the U.S. Securities and Exchange Commission (SEC) EDGAR database via REST API.
        * **Target Filings:** 
            * `Form 10-D`: Monthly distribution reports containing Trustee waterfall allocations and Overcollateralization (OC) metrics.
            * `Form ABS-EE`: Asset Data files containing loan-level XML data for delinquency roll-rates.
        
        **2. Stress Engine Mechanics:**
        * **Gross Defaults:** Calculated as `Current Pool Balance × Annualized CDR`.
        * **Net Losses:** Computed by applying the assumed recovery rate: `Gross Defaults × (1 - Recovery Rate)`.
        * **Stressed OC Ratio:** The Overcollateralization cushion is dynamically adjusted by subtracting the projected Net Losses from the Collateral Balance, keeping the Note Balance constant.
        
        **3. Trigger Evaluation:**
        * The engine continuously compares the Stressed OC Ratio against the deal's structural Target OC (defined in the Prospectus / Indenture).
        * A breach state simulates a *Sequential Pay* environment where cash flows are trapped to protect senior CP notes.
        """)